### ISSUE TITLE
翻译建议

### ISSUE THREAD

**Issue by ghost** [LocalizedMC/MgRbExtras-i18n#1]
@[TexBlock](https://github.com/TexBlock)
zh_cn:
![image](https://user-images.githubusercontent.com/76616758/178411946-1dbf8951-29fd-4303-91ad-e46f72535bb3.png)
![image](https://user-images.githubusercontent.com/76616758/178412066-bab3f00a-5e75-49c6-ae89-d3c2be827c95.png)
en_us:
![image](https://user-images.githubusercontent.com/76616758/178412380-f8af97bf-ee49-4616-8fc0-75927432c4c6.png)
![image](https://user-images.githubusercontent.com/76616758/178412397-1774f074-039b-4901-883a-c80e4fed792d.png)

提出建议：
zh_cn.json 中（从上到下）：
最大实体距离 -> 最大实体渲染距离
垂直实体距离 -> 垂直实体渲染距离
最大特殊方块渲染距离 -> 最大实体方块渲染距离
垂直实体距离 -> 垂直实体方块渲染距离
缩放效果 -> 缩放晕影
[来源](https://cn.bing.com/search?q=%E6%99%95%E5%BD%B1&cvid=a95696e0f35744f4b94b20a8ef129321&aqs=edge.0.69i59l3j69i60l6.2510j0j1&pglt=163&FORM=ANNTA1&PC=DCTS)：
![屏幕截图 2022-07-14 221350](https://user-images.githubusercontent.com/65154269/179003378-33cf15da-29a1-479a-bb52-86c866044e3c.png)

en_us.json 中：
Vertical Entity Distance ->Vertical Tile Distance
[原文如此](https://github.com/TeamDeusVult/MagnesiumExtras/blob/72bfccb9233b319cff58fb20ef879eb5362e92d0/src/main/java/vice/magnesium_extras/mixins/SodiumConfig/SodiumGameOptionsMixin.java#L224)

**Comment by TexBlock** [comment]
OK，今晚或明天发布修复版本
