### ISSUE TITLE
缩放功能失效

### ISSUE THREAD

**Issue by Landidi666** [LocalizedMC/MgRbExtras-i18n#2]
**运行环境：**
Java 11.0.12
Minecraft 1.16.5
Forge 36.2.39
还有下面的mod
![image](https://user-images.githubusercontent.com/104005371/180707339-f1b62599-0ac8-45af-b2f7-0b09d9f45113.png)

在游戏内按下缩放键没有任何效果，同一个版本的铷搭配官方版Rubidium Extras可以正常使用缩放

**Comment by TexBlock** [comment]
RubidiumExtra-1.3.2-Compatibility-Hotfix 试过吗，一样的问题吗

**Comment by Landidi666** [comment]
是的，也不能用缩放
不过1.16.5的镁+附属（Hotfix2）没问题

**Comment by TexBlock** [comment]
正在尝试修复（

**Comment by TexBlock** [comment]
已在 [mc1.16-v1.3.1-i18n-Multi](https://github.com/ForgeModi18n/MgRb-Extras-i18n/releases/tag/mc1.16-v1.3.1-i18n-Multi) 解决。
