### ISSUE TITLE
关于垂直实体渲染距离的Format error

### ISSUE THREAD

**Issue by qznfbnj** [LocalizedMC/MgRbExtras-i18n#4]
![rubidium_extras-1 18 2_v1 3 4-i18n](https://user-images.githubusercontent.com/100760086/183568826-916e2a28-c919-4497-8e6f-d5f1a065da2e.jpg)
https://github.com/ForgeModi18n/MgRb-Extras-i18n/blob/866c088930a71c62ad06641253969c6038d90c0e/src/main/java/vice/rubidium_extras/mixins/SodiumConfig/SodiumGameOptionsMixin.java#L218
这一行是忘记改了还是改了会出问题？我弄不好环境所以没法测试

**Comment by TexBlock** [comment]
在我测试的时候就出现过这个问题，原mod这里根本不会出现数值，会在下个版本修复

**Comment by qznfbnj** [comment]
> 在我测试的时候就出现过这个问题，原mod这里根本不会出现数值，会在下个版本修复

是这样的，我看你把get()都删了，猜是原始版本没做显示数字的东西，所以加个％s上去过不了i18n的审查哈哈（喂）

**Comment by TexBlock** [comment]
> > 在我测试的时候就出现过这个问题，原mod这里根本不会出现数值，会在下个版本修复
> 
> 是这样的，我看你把get()都删了，猜是原始版本没做显示数字的东西，所以加个％s上去过不了i18n的审查哈哈（喂）

确实，写本地化的时候写蒙了（

**Comment by TexBlock** [comment]
已在 [mc1.18-v1.3.4-i18n-Hotfix](https://github.com/ForgeModi18n/MgRb-Extras-i18n/releases/tag/mc1.18-v1.3.4-i18n-Hotfix) 修复 ~，我还没测试过，你先看看还有这个问题吗？~

**Comment by TexBlock** [comment]
尚未测试
